### PR TITLE
Fixes workflow event states unmarshalling methods

### PR DESCRIPTION
**Pull request by andresmijares**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
Actually, there's a small bug preventing to have `Event Switch State` and `Event Data State` on the same definition, this creates a small case where the other of the states only works if they are placed certain way, it's not deterministic.

We are using the sdk but we had to fork it in order to make it work correctly, I think, others will benefit from it.

How to reproduce it.

Given this definition:
```json
{
		"id": "testWorkflow",
		"name": "Validation Workflow Test",
		"version": "1.0",
		"specVersion": "0.7",
		"start": "Sample",
		"states": [
                       {
				"name": "Sample",
				"type": "switch",
				"dataConditions": [
				  {
					"condition": "${  .total > 10 }",
					"transition": "Sample2"
				  }
				]
		      },
                       {
				"name": "Sample2",
				"type": "switch",
				"eventConditions": [
					{						
                                                  "eventRef": "eventOne",
						"transition": "HandleEventFinishOne"
				  	},
					{
						"eventRef": "eventFinishTwo",
						"transition": "HandleEventFinishTwo"
				  	}
				]
			}
                 ]
}
```

[This line](https://github.com/serverlessworkflow/sdk-go/blob/main/model/workflow.go#L120) it's causing that when trying to unmashalling `Sample2`, `mapState` is not cleared for the next loop iteration, so `map[dataConditions]` is not `nil`. This cause [this line](https://github.com/serverlessworkflow/sdk-go/blob/main/model/workflow.go#L39) to be trigger wrongly, when there are 2 switch events and a `Switch Event Database` is place before the `Switch Event`.

Clearing  `mapState` before the next iteration of the loop should solve the issue.

Please, let me know, if anything else is needed.

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by ricardozanini — CHANGES_REQUESTED** [review]
Hi! Thanks for this change. Can you please add a unit test to validate the unmarshaling? Many thanks!

**Comment by andresmijares** [comment]
@ricardozanini should be good now, I added a small case with both states and making sure it compiles which is the small issue I'm solving, you can quickly confirm the issue changing the code back to the original way and run the test. Let me know if something else is required ^^. Thank u!

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@andresmijares let me know if you need a new patch release.

**Comment by andresmijares** [comment]
@ricardozanini after the merge, that would be great! i've been using a fork of the project only cause this :)

**Comment by ricardozanini** [comment]
> @ricardozanini after the merge, that would be great! i've been using a fork of the project only cause this :)

Actually, I'll upgrade the Go version and try to fix the CI. Something is not quite right. See #63

**Comment by ricardozanini** [comment]
@andresmijares, I've fixed all these CI bugs and dependencies problems here: #66 

Can you please take a look and try that PR locally to see if it's fine on your side so I can merge it? We then rebase this and do a release.

**Comment by andresmijares** [comment]
@ricardozanini i just sourced [this branch](https://github.com/ricardozanini/sdk-go/tree/issue-63) on my project and ran without problem (without considering the issues fixed in this PR)!

**Comment by ricardozanini** [comment]
@andresmijares can you rebase now that I've merged #63?

**Comment by andresmijares** [comment]
@ricardozanini done! thank you!

**Comment by andresmijares** [comment]
@ricardozanini last question, not related to the PR, is there any slack channel for ppl sharing ideas about this project?

**Comment by andresmijares** [comment]
i need an invitation, could u send me one pls? email is github user, gmail, thanks!!

**Comment by andresmijares** [comment]
@ricardozanini i think it's disabled, i tried joining and it says i dont have an account and i need one :(

**Comment by ricardozanini** [comment]
You just have to create a free account, I believe.

**Comment by andresmijares** [comment]
it seems it is set as invited only, not public joining option

**Comment by andresmijares** [comment]
thank you!

**Comment by ricardozanini** [comment]
Worked?

**Comment by andresmijares** [comment]
yes sir!

**Comment by ricardozanini** [comment]
Great, I'll update our docs.

**Pull request merged**
