### PR TITLE
Unmarshal state.end when boolean

### PR DESCRIPTION
**Pull request by ribeiromiranda**
**What this PR does / why we need it**:
Unmarshal state.end when boolean to follow the [end](https://github.com/serverlessworkflow/specification/blob/main/specification.md#end-definition) specification 

**Special notes for reviewers**:
Created test unit but I don't know is in the right place.

### CODE REVIEW

**Comment by spolti** [comment]
Hi @ribeiromiranda, many thanks for the PR :)

One suggestion, instead add the unit test to test only the State.End flag, you could reuse some of the ones that are already there and add just the assert. here for example: 
- https://github.com/serverlessworkflow/sdk-go/blob/main/parser/parser_test.go#L614
- https://github.com/serverlessworkflow/sdk-go/blob/main/parser/parser_test.go#L744

However, there are a big change on the States struct to be added, I would kindly ask you for the fix for https://github.com/serverlessworkflow/sdk-go/issues/144 be merged is it direct impacts your changes.

**Comment by ricardozanini** [comment]
@ribeiromiranda are you going to work on the suggestions made by @spolti?

**Comment by ribeiromiranda** [comment]
@spolti Can check? Thanks.

**Review by spolti — CHANGES_REQUESTED** [review]
this sounds good, however, can you please add some asserts in the marshal tests as well?

For example, here: https://github.com/serverlessworkflow/sdk-go/blob/main/parser/parser_test.go#L579

add a assert, like:
```
assert.True(t, strings.Contains(string(b), "\"end\":{\"terminate\":true}"))
```

**Comment by ribeiromiranda** [comment]
@spolit Add the test in the existing json.Marshal.

**Review by spolti — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Pull request closed without merging**
