### PR TITLE
Support to WebAssembly build

### PR DESCRIPTION
**Pull request by ribeiromiranda**
**What this PR does / why we need it**:
To build and execute the webassembly in a browser, electron, etc
```bash
GOOS=js GOARCH=wasm $(GO)  build -o out.wasm ./source/
```

**Special notes for reviewers**:
In my tests, the only need to change was the file manipulation.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by spolti** [comment]
Maybe we can have a issue describing better why it is needed and maybe a few instructions about how to use it?

**Comment by ricardozanini** [comment]
@spolti as I understood, this is needed for [WebAssembly](https://webassembly.org/) use cases.

**Comment by ricardozanini** [comment]
Not sure what you mean by documented use case, but I'm honestly curious to know more about @ribeiromiranda 's use case for the SDK and WebAssembly :)

**Comment by ribeiromiranda** [comment]
I'm developing a platform called [fermions](https://github.com/galgotech/fermions) for developers to design, build, test CloudEvents and Serverless workflow. To build a cross-platform desktop app, I'm using electron.

The [fermions-workflow](https://github.com/galgotech/fermions-workflow) (multiple platforms) use this sdk-go, builded with WebAssembly it's possible  run the workflows in electron or other web browser.

**Pull request merged**
