### PR TITLE
Improve model representation

### PR DESCRIPTION
**Pull request by desmax74**
When is called a representation the model structs lack of the information about the fields

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by spolti** [comment]
Hi @desmax74, is it still needed or can we close?

**Comment by desmax74** [comment]
@spolti yes because we can choose to use a useful representation in the logs when is called fmt.Printf

`fmt.Printf`

https://pkg.go.dev/fmt

> 5. If an operand implements method String(), that method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any). 

The {} in the String() is used just to avoid confusion with [] of the arrays/slices is not a replacement of json/yaml representation with marshal/unmarshal

**Comment by spolti** [comment]
@desmax74 I still don't have a strong opinion about the need of these String() funcs, parsing the workflow an d printing json pretty output is a way clearer.
Note that, you can parse snippets of the workflow as well.

@ricardozanini @lsytj0413 wdyt?

**Comment by lsytj0413** [comment]
> @desmax74 I still don't have a strong opinion about the need of these String() funcs, parsing the workflow an d printing json pretty output is a way clearer. Note that, you can parse snippets of the workflow as well.
> 
> @ricardozanini @lsytj0413 wdyt?

I didn't see the specific application scenarios or the problems that json.Marshal couldn't solve；On the other hand, if you want to see the specific information of each field, is [go-spec](https://github.com/davecgh/go-spew) an available option。

**Comment by desmax74** [comment]
@lsytj0413 go-spew fits well for the same purpose, thanks for the answer !

**Pull request closed without merging**
