### PR TITLE
fix(121): split inject state to separate file

### PR DESCRIPTION
**Pull request by lsytj0413**
Signed-off-by: lsytj0413 <511121939@qq.com>

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

Fixed https://github.com/serverlessworkflow/sdk-go/issues/121

### CODE REVIEW

**Comment by lsytj0413** [comment]
Hold by https://github.com/serverlessworkflow/specification/pull/703

**Comment by lsytj0413** [comment]
> we already have this timeouts for a while, why is it dependent?

Yes, base on v0.8 we can confirm the `timeouts` property is exists. We can merge this now.

**Comment by lsytj0413** [comment]
cc @ricardozanini  PTAL

**Comment by ricardozanini** [comment]
@lsytj0413 can you please rebase? I'm on PTO, so I have limited access to GH.

**Comment by lsytj0413** [comment]
> @lsytj0413 can you please rebase? I'm on PTO, so I have limited access to GH.

done, PTAL

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
