### PR TITLE
Fixing go tools installations

### PR DESCRIPTION
**Pull request by ricardozanini**

### CODE REVIEW

**Comment by ricardozanini** [comment]
@iwita could you please take a look and try this new `Makefile` in your local env?

**Comment by iwita** [comment]
> @iwita could you please take a look and try this new `Makefile` in your local env?

It does not seem to work. Actually, the addlicense binary is created in my ${GOPATH}/bin directory

**Comment by ricardozanini** [comment]
> > @iwita could you please take a look and try this new `Makefile` in your local env?
> 
> It does not seem to work. Actually, the addlicense binary is created in my ${GOPATH}/bin directory

Add `GOBIN` or `GOPATH` to your `PATH`.

**Comment by ricardozanini** [comment]
Since it's working for @iwita we are merging this one.

**Pull request merged**
