### PR TITLE
Fixes #25 - Sync with Spec 0.6

### LINKED ISSUE #25: Align SDK with specification 0.6
**What would you like to be added**:
We must align the SDK with the newly 0.6 version

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <ricardozanini@gmail.com>

Fixes #25

TODO:

- [x] Implement schema validation
- [x] Update test case data with 0.6 examples
- [x] Implement `End` as also a boolean field
- [x] Implement `string` or `struct` fields

### CODE REVIEW

**Comment by tsurdilo** [comment]
thats a big change-  ty!

**Comment by ricardozanini** [comment]
With this PR we can release 2.0.0 version, and expand the possibilities :)

**Comment by ricardozanini** [comment]
@iwita your review would be much appreciated

**Comment by iwita** [comment]
As far as I can judge, the PR seems to address both the new additions from the v0.6 specification( #25 ) and issue #16.

**Review by tsurdilo — APPROVED** [review]

**Pull request merged**
